### PR TITLE
Min SDK 16, bump dependency versions, update gradle & wrapper, fix linter error

### LINKED ISSUE #716: Android SDK should be minSdkVersion:21 (or earlier)
Currently it's at 26. API 21 is what our [android-components](https://github.com/mozilla-mobile/android-components) project is targeting, so mentat should be at the very least compatible with that.

### PR DESCRIPTION
**Pull request by grigoryk**
Fixes #716 and updates/cleans up things a little.

API 16 is chosen somewhat arbitrarily (this is what fennec currently uses).

### CODE REVIEW

File: sdks/android/Mentat/library/src/main/java/com/mozilla/mentat/InProgressTransactionResult.java [hunk 1]
```diff
@@ -41,7 +41,7 @@ public InProgress getInProgress() {
     
     public TxReport getReport() {
         if (this.result.isFailure()) {
-            Log.e("InProgressTransactionResult", this.result.err);
+            Log.e("InProgressTransactRes", this.result.err);
```
Comment (fluffyemily) [inline sdks/android/Mentat/library/src/main/java/com/mozilla/mentat/InProgressTransactionResult.java]: What was the reason for this log change?

Comment (rnewman) [reply sdks/android/Mentat/library/src/main/java/com/mozilla/mentat/InProgressTransactionResult.java]: Android log tags are limited to 23 characters in length. The original tag was 28.
